# Microprofile server properties
server:
  port: 8080
  host: 0.0.0.0

# Change the following to true to enable the optional MicroProfile Metrics REST.request metrics
metrics:
  rest-request:
    enabled: false

# Security config
security:
  config:
    require-encryption: false
  properties:
    keycloak-uri:
    keycloak-client-id:
    keycloak-client-secret:
    frontend-uri:
  providers:
    - abac:
    - oidc:
        client-id: ${security.properties.keycloak-client-id}
        client-secret: ${security.properties.keycloak-client-secret}
        identity-uri: ${security.properties.keycloak-uri}
        frontend-uri: ${security.properties.frontend-uri}
        audience: account
        base-scopes: openid cowsay:say
        # OIDC logout support
        logout-enabled: true
        post-logout-uri: /auth/logout
cowweb:
  endpoint-base:

org.eclipse.microprofile.rest.client.propagateHeaders: authorization
me.shukawam.auth.CowwebRestClient/mp-rest/uri: ${cowweb.endpoint-base}
