secretGenerator:
  - name: mysql-secret
    namespace: keycloak
    literals:
      - user=4b43b0aee356
      - rootPassword=8j4bB4ueiSCV
      - password=Dho2gK55dUFd
  - name: keycloak-password
    namespace: keycloak
    literals:
      - password=cww5x6movtdopbsf
resources:
  - mysql.yaml
  - keycloak.yaml
