apiVersion: v1
kind: Service
metadata:
  name: helidon-rp
  namespace: examples
  labels:
    app: helidon-rp
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  selector:
    app: helidon-rp
  ports:
    - port: 8080
      targetPort: 8080
      name: http
